### ISSUE TITLE
Exchange de fonctionne plus

### ISSUE THREAD

**Issue by just1602** [aclement30/Pilule#4]
Salut,

Depuis la mise à jour d'exchange vers Outlook Web App, l'ongle Exchange dans pilule ne fonctionne plus. J'ai une erreur 403 - forbidden.

![Erreur](http://s23.postimg.org/k9oh29ikb/pilule_exchange_forbidden.png)

**Comment by PaperbagWriter** [comment]
À noter que l'erreur survient lorsqu'on clique sur Exchange via le ul qui est un data-url du menu et que ça fonctionne via le dashboard qui est un a href qui fait simplement un redirect.
